kill_signal = "SIGINT"
kill_timeout = "3s"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    hard_limit = 15
    soft_limit = 10

[[services]]
  protocol = "tcp"
  internal_port = 7000

  [[services.ports]]
    port = 7000
