name: frp
description: Tunnel Home Assistant to WAN (if you're behind a CG-nat or Firewall)
version: 1.0.1
url: https://github.com/hannpet/addon-frpc
startup: application
boot: auto
host_network: true
slug: frp
init: false
arch:
  - aarch64
  - amd64
map:
  - config:rw
  - ssl:rw
  - backup:rw

options:
  server_addr: null
  server_port: 7000
  token_key: null
  local_port: 80
  
schema:
  server_addr: str
  server_port: port
  token_key: str
  local_port: port